import type { Metadata } from "next";
import "@/styles/globals.css";
import { Header, Sidebar } from "@/components";
import { inter } from "@/fonts";
export const metadata: Metadata = {
  title: "Bank Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Sidebar />
        <Header title="Overview" />
        <main className="content">{children}</main>
      </body>
    </html>
  );
}
